/* Generated by Yosys 0.9 (git sha1 1979e0b1, gcc 10.3.0-1ubuntu1~20.10 -fPIC -Os) */

(* top =  1  *)
(* src = "pixelState.v:3" *)
module pixelState(clk, reset, erase, expose, read1, read2, read3, read4, convert);
  (* src = "pixelState.v:49" *)
  wire _000_;
  (* src = "pixelState.v:49" *)
  wire _001_;
  (* src = "pixelState.v:49" *)
  wire _002_;
  (* src = "pixelState.v:24" *)
  wire [7:0] _003_;
  (* src = "pixelState.v:128" *)
  wire [2:0] _004_;
  (* src = "pixelState.v:24" *)
  wire [7:0] _005_;
  (* src = "pixelState.v:49" *)
  wire _006_;
  (* src = "pixelState.v:49" *)
  wire _007_;
  (* src = "pixelState.v:49" *)
  wire _008_;
  (* src = "pixelState.v:49" *)
  wire _009_;
  (* src = "pixelState.v:128" *)
  wire _010_;
  (* src = "pixelState.v:128" *)
  wire [2:0] _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  (* src = "pixelState.v:49" *)
  wire _140_;
  (* src = "pixelState.v:49" *)
  wire _141_;
  (* src = "pixelState.v:49" *)
  wire _142_;
  (* src = "pixelState.v:24" *)
  wire _143_;
  (* src = "pixelState.v:24" *)
  wire _144_;
  (* src = "pixelState.v:24" *)
  wire _145_;
  (* src = "pixelState.v:24" *)
  wire _146_;
  (* src = "pixelState.v:24" *)
  wire _147_;
  (* src = "pixelState.v:24" *)
  wire _148_;
  (* src = "pixelState.v:24" *)
  wire _149_;
  (* src = "pixelState.v:128" *)
  wire _150_;
  (* src = "pixelState.v:128" *)
  wire _151_;
  (* src = "pixelState.v:128" *)
  wire _152_;
  (* src = "pixelState.v:24" *)
  wire _153_;
  (* src = "pixelState.v:24" *)
  wire _154_;
  (* src = "pixelState.v:24" *)
  wire _155_;
  (* src = "pixelState.v:24" *)
  wire _156_;
  (* src = "pixelState.v:24" *)
  wire _157_;
  (* src = "pixelState.v:24" *)
  wire _158_;
  (* src = "pixelState.v:49" *)
  wire _159_;
  (* src = "pixelState.v:49" *)
  wire _160_;
  (* src = "pixelState.v:49" *)
  wire _161_;
  (* src = "pixelState.v:49" *)
  wire _162_;
  (* src = "pixelState.v:128" *)
  wire _163_;
  (* src = "pixelState.v:128" *)
  wire _164_;
  (* src = "pixelState.v:128" *)
  wire _165_;
  (* src = "pixelState.v:128" *)
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  (* src = "pixelState.v:4" *)
  wire _194_;
  (* src = "pixelState.v:20" *)
  wire _195_;
  (* src = "pixelState.v:20" *)
  wire _196_;
  (* src = "pixelState.v:20" *)
  wire _197_;
  (* src = "pixelState.v:20" *)
  wire _198_;
  (* src = "pixelState.v:20" *)
  wire _199_;
  (* src = "pixelState.v:20" *)
  wire _200_;
  (* src = "pixelState.v:20" *)
  wire _201_;
  (* src = "pixelState.v:20" *)
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  (* src = "pixelState.v:40" *)
  wire _367_;
  (* src = "pixelState.v:40" *)
  wire _368_;
  (* src = "pixelState.v:40" *)
  wire _369_;
  (* src = "pixelState.v:22" *)
  wire _370_;
  (* src = "pixelState.v:22" *)
  wire _371_;
  (* src = "pixelState.v:22" *)
  wire _372_;
  (* src = "pixelState.v:22" *)
  wire _373_;
  (* src = "pixelState.v:22" *)
  wire _374_;
  (* src = "pixelState.v:22" *)
  wire _375_;
  (* src = "pixelState.v:22" *)
  wire _376_;
  (* src = "pixelState.v:22" *)
  wire _377_;
  (* src = "pixelState.v:23" *)
  wire _378_;
  (* src = "pixelState.v:40" *)
  wire _379_;
  (* src = "pixelState.v:40" *)
  wire _380_;
  (* src = "pixelState.v:40" *)
  wire _381_;
  wire _382_;
  wire _383_;
  wire _384_;
  wire _385_;
  wire _386_;
  wire _387_;
  wire _388_;
  wire _389_;
  wire _390_;
  wire _391_;
  wire _392_;
  wire _393_;
  wire _394_;
  wire _395_;
  wire _396_;
  wire _397_;
  wire _398_;
  wire _399_;
  wire _400_;
  wire _401_;
  wire _402_;
  wire _403_;
  wire _404_;
  wire _405_;
  wire _406_;
  wire _407_;
  wire _408_;
  wire _409_;
  wire _410_;
  wire _411_;
  wire _412_;
  wire _413_;
  wire _414_;
  wire _415_;
  wire _416_;
  wire _417_;
  wire _418_;
  wire _419_;
  wire _420_;
  wire _421_;
  wire _422_;
  wire _423_;
  (* src = "pixelState.v:4" *)
  input clk;
  (* src = "pixelState.v:12" *)
  output convert;
  (* src = "pixelState.v:21" *)
  wire enable_counter;
  (* src = "pixelState.v:6" *)
  output erase;
  (* src = "pixelState.v:7" *)
  output expose;
  (* src = "pixelState.v:20" *)
  wire [7:0] gray_counter;
  (* src = "pixelState.v:40" *)
  wire [2:0] next_state;
  (* src = "pixelState.v:22" *)
  wire [7:0] q;
  (* src = "pixelState.v:8" *)
  output read1;
  (* src = "pixelState.v:9" *)
  output read2;
  (* src = "pixelState.v:10" *)
  output read3;
  (* src = "pixelState.v:11" *)
  output read4;
  (* src = "pixelState.v:5" *)
  input reset;
  (* init = 1'h0 *)
  (* src = "pixelState.v:23" *)
  wire reset_c;
  (* src = "pixelState.v:40" *)
  wire [2:0] state;
  IVX1_CV _424_ (
    .A(_380_),
    .Y(_348_)
  );
  IVX1_CV _425_ (
    .A(_379_),
    .Y(_349_)
  );
  IVX1_CV _426_ (
    .A(_183_),
    .Y(_350_)
  );
  IVX1_CV _427_ (
    .A(_381_),
    .Y(_351_)
  );
  IVX1_CV _428_ (
    .A(_370_),
    .Y(_352_)
  );
  IVX1_CV _429_ (
    .A(_371_),
    .Y(_353_)
  );
  IVX1_CV _430_ (
    .A(_378_),
    .Y(_354_)
  );
  IVX1_CV _431_ (
    .A(_373_),
    .Y(_355_)
  );
  IVX1_CV _432_ (
    .A(_375_),
    .Y(_356_)
  );
  IVX1_CV _433_ (
    .A(_200_),
    .Y(_357_)
  );
  IVX1_CV _434_ (
    .A(_202_),
    .Y(_358_)
  );
  IVX1_CV _435_ (
    .A(_184_),
    .Y(_359_)
  );
  IVX1_CV _436_ (
    .A(_185_),
    .Y(_360_)
  );
  IVX1_CV _437_ (
    .A(_194_),
    .Y(_187_)
  );
  NRX1_CV _438_ (
    .A(_380_),
    .B(_183_),
    .Y(_361_)
  );
  NRX1_CV _439_ (
    .A(_380_),
    .B(_349_),
    .Y(_362_)
  );
  NDX1_CV _440_ (
    .A(_379_),
    .B(_361_),
    .Y(_363_)
  );
  IVX1_CV _441_ (
    .A(_363_),
    .Y(_161_)
  );
  NRX1_CV _442_ (
    .A(_348_),
    .B(_379_),
    .Y(_364_)
  );
  NDX1_CV _443_ (
    .A(_380_),
    .B(_349_),
    .Y(_365_)
  );
  NDX1_CV _444_ (
    .A(_349_),
    .B(_381_),
    .Y(_366_)
  );
  NRX1_CV _445_ (
    .A(_348_),
    .B(_366_),
    .Y(_162_)
  );
  NDX1_CV _446_ (
    .A(_380_),
    .B(_379_),
    .Y(_203_)
  );
  IVX1_CV _447_ (
    .A(_203_),
    .Y(_204_)
  );
  NRX1_CV _448_ (
    .A(_350_),
    .B(_203_),
    .Y(_159_)
  );
  NRX1_CV _449_ (
    .A(_380_),
    .B(_379_),
    .Y(_205_)
  );
  NRX1_CV _450_ (
    .A(_380_),
    .B(_366_),
    .Y(_160_)
  );
  NDX1_CV _451_ (
    .A(_183_),
    .B(_364_),
    .Y(_206_)
  );
  IVX1_CV _452_ (
    .A(_206_),
    .Y(_140_)
  );
  NDX1_CV _453_ (
    .A(_183_),
    .B(_362_),
    .Y(_207_)
  );
  IVX1_CV _454_ (
    .A(_207_),
    .Y(_142_)
  );
  NRX1_CV _455_ (
    .A(_348_),
    .B(_183_),
    .Y(_208_)
  );
  NDX1_CV _456_ (
    .A(_380_),
    .B(_350_),
    .Y(_209_)
  );
  NRX1_CV _457_ (
    .A(_183_),
    .B(_203_),
    .Y(_163_)
  );
  IVX1_CV _458_ (
    .A(_163_),
    .Y(_210_)
  );
  NDX1_CV _459_ (
    .A(_351_),
    .B(_205_),
    .Y(_211_)
  );
  IVX1_CV _460_ (
    .A(_211_),
    .Y(_141_)
  );
  NRX1_CV _461_ (
    .A(_370_),
    .B(_371_),
    .Y(_212_)
  );
  NRX1_CV _462_ (
    .A(_352_),
    .B(_353_),
    .Y(_213_)
  );
  NRX1_CV _463_ (
    .A(_212_),
    .B(_213_),
    .Y(_143_)
  );
  NDX1_CV _464_ (
    .A(_378_),
    .B(_143_),
    .Y(_214_)
  );
  IVX1_CV _465_ (
    .A(_214_),
    .Y(_167_)
  );
  NRX1_CV _466_ (
    .A(_371_),
    .B(_372_),
    .Y(_215_)
  );
  NDX1_CV _467_ (
    .A(_371_),
    .B(_372_),
    .Y(_216_)
  );
  IVX1_CV _468_ (
    .A(_216_),
    .Y(_217_)
  );
  NRX1_CV _469_ (
    .A(_215_),
    .B(_217_),
    .Y(_144_)
  );
  NDX1_CV _470_ (
    .A(_378_),
    .B(_144_),
    .Y(_218_)
  );
  IVX1_CV _471_ (
    .A(_218_),
    .Y(_168_)
  );
  NRX1_CV _472_ (
    .A(_372_),
    .B(_373_),
    .Y(_219_)
  );
  NDX1_CV _473_ (
    .A(_372_),
    .B(_373_),
    .Y(_220_)
  );
  IVX1_CV _474_ (
    .A(_220_),
    .Y(_221_)
  );
  NRX1_CV _475_ (
    .A(_219_),
    .B(_221_),
    .Y(_145_)
  );
  NDX1_CV _476_ (
    .A(_378_),
    .B(_145_),
    .Y(_222_)
  );
  IVX1_CV _477_ (
    .A(_222_),
    .Y(_169_)
  );
  NRX1_CV _478_ (
    .A(_373_),
    .B(_374_),
    .Y(_223_)
  );
  NDX1_CV _479_ (
    .A(_373_),
    .B(_374_),
    .Y(_224_)
  );
  IVX1_CV _480_ (
    .A(_224_),
    .Y(_225_)
  );
  NRX1_CV _481_ (
    .A(_223_),
    .B(_225_),
    .Y(_146_)
  );
  NDX1_CV _482_ (
    .A(_378_),
    .B(_146_),
    .Y(_226_)
  );
  IVX1_CV _483_ (
    .A(_226_),
    .Y(_170_)
  );
  NRX1_CV _484_ (
    .A(_374_),
    .B(_375_),
    .Y(_227_)
  );
  NDX1_CV _485_ (
    .A(_374_),
    .B(_375_),
    .Y(_228_)
  );
  IVX1_CV _486_ (
    .A(_228_),
    .Y(_229_)
  );
  NRX1_CV _487_ (
    .A(_227_),
    .B(_229_),
    .Y(_147_)
  );
  NDX1_CV _488_ (
    .A(_378_),
    .B(_147_),
    .Y(_230_)
  );
  IVX1_CV _489_ (
    .A(_230_),
    .Y(_171_)
  );
  NRX1_CV _490_ (
    .A(_375_),
    .B(_376_),
    .Y(_231_)
  );
  NDX1_CV _491_ (
    .A(_375_),
    .B(_376_),
    .Y(_232_)
  );
  IVX1_CV _492_ (
    .A(_232_),
    .Y(_233_)
  );
  NRX1_CV _493_ (
    .A(_231_),
    .B(_233_),
    .Y(_148_)
  );
  NDX1_CV _494_ (
    .A(_378_),
    .B(_148_),
    .Y(_234_)
  );
  IVX1_CV _495_ (
    .A(_234_),
    .Y(_172_)
  );
  NRX1_CV _496_ (
    .A(_376_),
    .B(_377_),
    .Y(_235_)
  );
  NDX1_CV _497_ (
    .A(_376_),
    .B(_377_),
    .Y(_236_)
  );
  IVX1_CV _498_ (
    .A(_236_),
    .Y(_237_)
  );
  NRX1_CV _499_ (
    .A(_235_),
    .B(_237_),
    .Y(_149_)
  );
  NDX1_CV _500_ (
    .A(_378_),
    .B(_149_),
    .Y(_238_)
  );
  IVX1_CV _501_ (
    .A(_238_),
    .Y(_173_)
  );
  NDX1_CV _502_ (
    .A(_378_),
    .B(_377_),
    .Y(_239_)
  );
  IVX1_CV _503_ (
    .A(_239_),
    .Y(_174_)
  );
  NRX1_CV _504_ (
    .A(_354_),
    .B(_143_),
    .Y(_175_)
  );
  NRX1_CV _505_ (
    .A(_354_),
    .B(_144_),
    .Y(_176_)
  );
  NRX1_CV _506_ (
    .A(_354_),
    .B(_145_),
    .Y(_177_)
  );
  NRX1_CV _507_ (
    .A(_354_),
    .B(_146_),
    .Y(_178_)
  );
  NRX1_CV _508_ (
    .A(_354_),
    .B(_147_),
    .Y(_179_)
  );
  NRX1_CV _509_ (
    .A(_354_),
    .B(_148_),
    .Y(_180_)
  );
  NRX1_CV _510_ (
    .A(_354_),
    .B(_149_),
    .Y(_181_)
  );
  NRX1_CV _511_ (
    .A(_354_),
    .B(_377_),
    .Y(_182_)
  );
  NDX1_CV _512_ (
    .A(_366_),
    .B(_208_),
    .Y(_240_)
  );
  IVX1_CV _513_ (
    .A(_240_),
    .Y(_241_)
  );
  NRX1_CV _514_ (
    .A(_367_),
    .B(_240_),
    .Y(_242_)
  );
  NDX1_CV _515_ (
    .A(_196_),
    .B(_198_),
    .Y(_243_)
  );
  IVX1_CV _516_ (
    .A(_243_),
    .Y(_244_)
  );
  NDX1_CV _517_ (
    .A(_195_),
    .B(_197_),
    .Y(_245_)
  );
  IVX1_CV _518_ (
    .A(_245_),
    .Y(_246_)
  );
  NDX1_CV _519_ (
    .A(_199_),
    .B(_202_),
    .Y(_247_)
  );
  NRX1_CV _520_ (
    .A(_358_),
    .B(_245_),
    .Y(_248_)
  );
  NRX1_CV _521_ (
    .A(_245_),
    .B(_247_),
    .Y(_249_)
  );
  NDX1_CV _522_ (
    .A(_199_),
    .B(_248_),
    .Y(_250_)
  );
  NDX1_CV _523_ (
    .A(_200_),
    .B(_201_),
    .Y(_251_)
  );
  NRX1_CV _524_ (
    .A(_357_),
    .B(_243_),
    .Y(_252_)
  );
  NRX1_CV _525_ (
    .A(_243_),
    .B(_251_),
    .Y(_253_)
  );
  NDX1_CV _526_ (
    .A(_201_),
    .B(_252_),
    .Y(_254_)
  );
  NRX1_CV _527_ (
    .A(_250_),
    .B(_254_),
    .Y(_255_)
  );
  NDX1_CV _528_ (
    .A(_249_),
    .B(_253_),
    .Y(_256_)
  );
  NDX1_CV _529_ (
    .A(_362_),
    .B(_256_),
    .Y(_257_)
  );
  NDX1_CV _530_ (
    .A(_365_),
    .B(_257_),
    .Y(_258_)
  );
  NRX1_CV _531_ (
    .A(_367_),
    .B(_255_),
    .Y(_259_)
  );
  NRX1_CV _532_ (
    .A(_381_),
    .B(_259_),
    .Y(_260_)
  );
  NDX1_CV _533_ (
    .A(_258_),
    .B(_260_),
    .Y(_261_)
  );
  NRX1_CV _534_ (
    .A(_381_),
    .B(_203_),
    .Y(_262_)
  );
  NDX1_CV _535_ (
    .A(_351_),
    .B(_204_),
    .Y(_263_)
  );
  NRX1_CV _536_ (
    .A(_183_),
    .B(_204_),
    .Y(_264_)
  );
  NDX1_CV _537_ (
    .A(_350_),
    .B(_203_),
    .Y(_265_)
  );
  NRX1_CV _538_ (
    .A(_262_),
    .B(_264_),
    .Y(_266_)
  );
  NDX1_CV _539_ (
    .A(_263_),
    .B(_265_),
    .Y(_267_)
  );
  NRX1_CV _540_ (
    .A(_200_),
    .B(_199_),
    .Y(_268_)
  );
  NRX1_CV _541_ (
    .A(_202_),
    .B(_201_),
    .Y(_269_)
  );
  NDX1_CV _542_ (
    .A(_268_),
    .B(_269_),
    .Y(_270_)
  );
  NRX1_CV _543_ (
    .A(_195_),
    .B(_197_),
    .Y(_271_)
  );
  NDX1_CV _544_ (
    .A(_244_),
    .B(_271_),
    .Y(_272_)
  );
  NRX1_CV _545_ (
    .A(_270_),
    .B(_272_),
    .Y(_273_)
  );
  NDX1_CV _546_ (
    .A(_349_),
    .B(_361_),
    .Y(_274_)
  );
  NRX1_CV _547_ (
    .A(_367_),
    .B(_273_),
    .Y(_275_)
  );
  NDX1_CV _548_ (
    .A(_273_),
    .B(_274_),
    .Y(_276_)
  );
  NDX1_CV _549_ (
    .A(_267_),
    .B(_276_),
    .Y(_277_)
  );
  NRX1_CV _550_ (
    .A(_275_),
    .B(_277_),
    .Y(_278_)
  );
  NRX1_CV _551_ (
    .A(_196_),
    .B(_198_),
    .Y(_279_)
  );
  NDX1_CV _552_ (
    .A(_246_),
    .B(_279_),
    .Y(_280_)
  );
  NRX1_CV _553_ (
    .A(_270_),
    .B(_280_),
    .Y(_281_)
  );
  IVX1_CV _554_ (
    .A(_281_),
    .Y(_282_)
  );
  NRX1_CV _555_ (
    .A(_211_),
    .B(_282_),
    .Y(_283_)
  );
  NRX1_CV _556_ (
    .A(_184_),
    .B(_211_),
    .Y(_284_)
  );
  IVX1_CV _557_ (
    .A(_284_),
    .Y(_285_)
  );
  NDX1_CV _558_ (
    .A(_240_),
    .B(_285_),
    .Y(_286_)
  );
  NRX1_CV _559_ (
    .A(_283_),
    .B(_286_),
    .Y(_287_)
  );
  NDX1_CV _560_ (
    .A(_261_),
    .B(_287_),
    .Y(_288_)
  );
  NRX1_CV _561_ (
    .A(_278_),
    .B(_288_),
    .Y(_289_)
  );
  NRX1_CV _562_ (
    .A(_242_),
    .B(_289_),
    .Y(_150_)
  );
  NDX1_CV _563_ (
    .A(_206_),
    .B(_207_),
    .Y(_290_)
  );
  IVX1_CV _564_ (
    .A(_290_),
    .Y(_291_)
  );
  NRX1_CV _565_ (
    .A(_211_),
    .B(_281_),
    .Y(_292_)
  );
  NRX1_CV _566_ (
    .A(_241_),
    .B(_292_),
    .Y(_293_)
  );
  NDX1_CV _567_ (
    .A(_291_),
    .B(_293_),
    .Y(_294_)
  );
  NDX1_CV _568_ (
    .A(_368_),
    .B(_294_),
    .Y(_295_)
  );
  NDX1_CV _569_ (
    .A(_255_),
    .B(_290_),
    .Y(_296_)
  );
  NDX1_CV _570_ (
    .A(_363_),
    .B(_273_),
    .Y(_297_)
  );
  NRX1_CV _571_ (
    .A(_368_),
    .B(_273_),
    .Y(_298_)
  );
  NRX1_CV _572_ (
    .A(_266_),
    .B(_298_),
    .Y(_299_)
  );
  NDX1_CV _573_ (
    .A(_297_),
    .B(_299_),
    .Y(_300_)
  );
  NDX1_CV _574_ (
    .A(_296_),
    .B(_300_),
    .Y(_301_)
  );
  NDX1_CV _575_ (
    .A(_240_),
    .B(_301_),
    .Y(_302_)
  );
  NDX1_CV _576_ (
    .A(_295_),
    .B(_302_),
    .Y(_151_)
  );
  NRX1_CV _577_ (
    .A(_209_),
    .B(_273_),
    .Y(_303_)
  );
  NDX1_CV _578_ (
    .A(_349_),
    .B(_303_),
    .Y(_304_)
  );
  NDX1_CV _579_ (
    .A(_293_),
    .B(_304_),
    .Y(_305_)
  );
  NDX1_CV _580_ (
    .A(_369_),
    .B(_305_),
    .Y(_306_)
  );
  NRX1_CV _581_ (
    .A(_369_),
    .B(_273_),
    .Y(_307_)
  );
  NRX1_CV _582_ (
    .A(_361_),
    .B(_262_),
    .Y(_308_)
  );
  NRX1_CV _583_ (
    .A(_307_),
    .B(_308_),
    .Y(_309_)
  );
  NDX1_CV _584_ (
    .A(_256_),
    .B(_290_),
    .Y(_310_)
  );
  NRX1_CV _585_ (
    .A(_186_),
    .B(_310_),
    .Y(_311_)
  );
  NRX1_CV _586_ (
    .A(_309_),
    .B(_311_),
    .Y(_312_)
  );
  IVX1_CV _587_ (
    .A(_312_),
    .Y(_313_)
  );
  NDX1_CV _588_ (
    .A(_240_),
    .B(_313_),
    .Y(_314_)
  );
  NDX1_CV _589_ (
    .A(_306_),
    .B(_314_),
    .Y(_152_)
  );
  NDX1_CV _590_ (
    .A(_381_),
    .B(_203_),
    .Y(_315_)
  );
  NDX1_CV _591_ (
    .A(_263_),
    .B(_315_),
    .Y(_316_)
  );
  NDX1_CV _592_ (
    .A(_273_),
    .B(_316_),
    .Y(_317_)
  );
  NDX1_CV _593_ (
    .A(_296_),
    .B(_317_),
    .Y(_318_)
  );
  NRX1_CV _594_ (
    .A(_379_),
    .B(_318_),
    .Y(_319_)
  );
  NRX1_CV _595_ (
    .A(_351_),
    .B(_163_),
    .Y(_320_)
  );
  NDX1_CV _596_ (
    .A(_381_),
    .B(_163_),
    .Y(_321_)
  );
  NDX1_CV _597_ (
    .A(_211_),
    .B(_321_),
    .Y(_322_)
  );
  NRX1_CV _598_ (
    .A(_319_),
    .B(_322_),
    .Y(_323_)
  );
  NDX1_CV _599_ (
    .A(_359_),
    .B(_163_),
    .Y(_324_)
  );
  NRX1_CV _600_ (
    .A(_283_),
    .B(_323_),
    .Y(_325_)
  );
  NDX1_CV _601_ (
    .A(_324_),
    .B(_325_),
    .Y(_164_)
  );
  NRX1_CV _602_ (
    .A(_380_),
    .B(_318_),
    .Y(_326_)
  );
  NRX1_CV _603_ (
    .A(_322_),
    .B(_326_),
    .Y(_327_)
  );
  NDX1_CV _604_ (
    .A(_360_),
    .B(_163_),
    .Y(_328_)
  );
  NRX1_CV _605_ (
    .A(_283_),
    .B(_327_),
    .Y(_329_)
  );
  NDX1_CV _606_ (
    .A(_328_),
    .B(_329_),
    .Y(_165_)
  );
  NRX1_CV _607_ (
    .A(_186_),
    .B(_210_),
    .Y(_330_)
  );
  NRX1_CV _608_ (
    .A(_320_),
    .B(_330_),
    .Y(_331_)
  );
  NRX1_CV _609_ (
    .A(_283_),
    .B(_318_),
    .Y(_332_)
  );
  NDX1_CV _610_ (
    .A(_331_),
    .B(_332_),
    .Y(_166_)
  );
  NRX1_CV _611_ (
    .A(_352_),
    .B(_216_),
    .Y(_333_)
  );
  NDX1_CV _612_ (
    .A(_372_),
    .B(_213_),
    .Y(_334_)
  );
  NRX1_CV _613_ (
    .A(_372_),
    .B(_213_),
    .Y(_335_)
  );
  NRX1_CV _614_ (
    .A(_333_),
    .B(_335_),
    .Y(_153_)
  );
  NRX1_CV _615_ (
    .A(_355_),
    .B(_334_),
    .Y(_336_)
  );
  NRX1_CV _616_ (
    .A(_373_),
    .B(_333_),
    .Y(_337_)
  );
  NRX1_CV _617_ (
    .A(_336_),
    .B(_337_),
    .Y(_154_)
  );
  NRX1_CV _618_ (
    .A(_224_),
    .B(_334_),
    .Y(_338_)
  );
  NDX1_CV _619_ (
    .A(_225_),
    .B(_333_),
    .Y(_339_)
  );
  NRX1_CV _620_ (
    .A(_374_),
    .B(_336_),
    .Y(_340_)
  );
  NRX1_CV _621_ (
    .A(_338_),
    .B(_340_),
    .Y(_155_)
  );
  NRX1_CV _622_ (
    .A(_375_),
    .B(_338_),
    .Y(_341_)
  );
  NRX1_CV _623_ (
    .A(_356_),
    .B(_339_),
    .Y(_342_)
  );
  NRX1_CV _624_ (
    .A(_341_),
    .B(_342_),
    .Y(_156_)
  );
  NRX1_CV _625_ (
    .A(_232_),
    .B(_339_),
    .Y(_343_)
  );
  NRX1_CV _626_ (
    .A(_376_),
    .B(_342_),
    .Y(_344_)
  );
  NRX1_CV _627_ (
    .A(_343_),
    .B(_344_),
    .Y(_157_)
  );
  NRX1_CV _628_ (
    .A(_377_),
    .B(_343_),
    .Y(_345_)
  );
  NDX1_CV _629_ (
    .A(_377_),
    .B(_343_),
    .Y(_346_)
  );
  IVX1_CV _630_ (
    .A(_346_),
    .Y(_347_)
  );
  NRX1_CV _631_ (
    .A(_345_),
    .B(_347_),
    .Y(_158_)
  );
  IVX1_CV _632_ (
    .A(_194_),
    .Y(_188_)
  );
  IVX1_CV _633_ (
    .A(_194_),
    .Y(_189_)
  );
  IVX1_CV _634_ (
    .A(_194_),
    .Y(_190_)
  );
  IVX1_CV _635_ (
    .A(_194_),
    .Y(_191_)
  );
  IVX1_CV _636_ (
    .A(_194_),
    .Y(_192_)
  );
  IVX1_CV _637_ (
    .A(_194_),
    .Y(_193_)
  );
  (* src = "pixelState.v:49" *)
  DFSRQNX1_CV _638_ (
    .CK(_417_),
    .D(_008_),
    .Q(read3),
    .QN(_382_),
    .R(1'h0),
    .S(1'h0)
  );
  (* src = "pixelState.v:49" *)
  DFSRQNX1_CV _639_ (
    .CK(_418_),
    .D(_009_),
    .Q(read4),
    .QN(_383_),
    .R(1'h0),
    .S(1'h0)
  );
  (* src = "pixelState.v:49" *)
  DFSRQNX1_CV _640_ (
    .CK(_419_),
    .D(_000_),
    .Q(convert),
    .QN(_384_),
    .R(1'h0),
    .S(1'h0)
  );
  (* src = "pixelState.v:49" *)
  DFSRQNX1_CV _641_ (
    .CK(_420_),
    .D(_006_),
    .Q(read1),
    .QN(_385_),
    .R(1'h0),
    .S(1'h0)
  );
  (* src = "pixelState.v:49" *)
  DFSRQNX1_CV _642_ (
    .CK(_421_),
    .D(_007_),
    .Q(read2),
    .QN(_386_),
    .R(1'h0),
    .S(1'h0)
  );
  (* src = "pixelState.v:49" *)
  DFSRQNX1_CV _643_ (
    .CK(_422_),
    .D(_001_),
    .Q(erase),
    .QN(_387_),
    .R(1'h0),
    .S(1'h0)
  );
  (* src = "pixelState.v:49" *)
  DFSRQNX1_CV _644_ (
    .CK(_423_),
    .D(_002_),
    .Q(expose),
    .QN(_388_),
    .R(1'h0),
    .S(1'h0)
  );
  (* src = "pixelState.v:24" *)
  DFSRQNX1_CV _645_ (
    .CK(clk),
    .D(_003_[0]),
    .Q(gray_counter[0]),
    .QN(_389_),
    .R(_020_),
    .S(_012_)
  );
  (* src = "pixelState.v:24" *)
  DFSRQNX1_CV _646_ (
    .CK(clk),
    .D(_003_[1]),
    .Q(gray_counter[1]),
    .QN(_390_),
    .R(_021_),
    .S(_013_)
  );
  (* src = "pixelState.v:24" *)
  DFSRQNX1_CV _647_ (
    .CK(clk),
    .D(_003_[2]),
    .Q(gray_counter[2]),
    .QN(_391_),
    .R(_022_),
    .S(_014_)
  );
  (* src = "pixelState.v:24" *)
  DFSRQNX1_CV _648_ (
    .CK(clk),
    .D(_003_[3]),
    .Q(gray_counter[3]),
    .QN(_392_),
    .R(_023_),
    .S(_015_)
  );
  (* src = "pixelState.v:24" *)
  DFSRQNX1_CV _649_ (
    .CK(clk),
    .D(_003_[4]),
    .Q(gray_counter[4]),
    .QN(_393_),
    .R(_024_),
    .S(_016_)
  );
  (* src = "pixelState.v:24" *)
  DFSRQNX1_CV _650_ (
    .CK(clk),
    .D(_003_[5]),
    .Q(gray_counter[5]),
    .QN(_394_),
    .R(_025_),
    .S(_017_)
  );
  (* src = "pixelState.v:24" *)
  DFSRQNX1_CV _651_ (
    .CK(clk),
    .D(_003_[6]),
    .Q(gray_counter[6]),
    .QN(_395_),
    .R(_026_),
    .S(_018_)
  );
  (* src = "pixelState.v:24" *)
  DFSRQNX1_CV _652_ (
    .CK(clk),
    .D(q[7]),
    .Q(gray_counter[7]),
    .QN(_396_),
    .R(_027_),
    .S(_019_)
  );
  (* src = "pixelState.v:128" *)
  DFSRQNX1_CV _653_ (
    .CK(clk),
    .D(_010_),
    .Q(reset_c),
    .QN(_397_),
    .R(1'h0),
    .S(reset)
  );
  (* src = "pixelState.v:128" *)
  DFSRQNX1_CV _654_ (
    .CK(clk),
    .D(_011_[0]),
    .Q(state[0]),
    .QN(_398_),
    .R(1'h0),
    .S(reset)
  );
  (* src = "pixelState.v:128" *)
  DFSRQNX1_CV _655_ (
    .CK(clk),
    .D(_011_[1]),
    .Q(state[1]),
    .QN(_399_),
    .R(1'h0),
    .S(reset)
  );
  (* src = "pixelState.v:128" *)
  DFSRQNX1_CV _656_ (
    .CK(clk),
    .D(_011_[2]),
    .Q(state[2]),
    .QN(_400_),
    .R(1'h0),
    .S(reset)
  );
  (* src = "pixelState.v:128" *)
  DFSRQNX1_CV _657_ (
    .CK(clk),
    .D(_004_[0]),
    .Q(next_state[0]),
    .QN(_401_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelState.v:128" *)
  DFSRQNX1_CV _658_ (
    .CK(clk),
    .D(_004_[1]),
    .Q(next_state[1]),
    .QN(_402_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelState.v:128" *)
  DFSRQNX1_CV _659_ (
    .CK(clk),
    .D(_004_[2]),
    .Q(next_state[2]),
    .QN(_403_),
    .R(reset),
    .S(1'h0)
  );
  (* src = "pixelState.v:24" *)
  DFSRQNX1_CV _660_ (
    .CK(clk),
    .D(_005_[0]),
    .Q(q[0]),
    .QN(_404_),
    .R(reset_c),
    .S(1'h0)
  );
  (* src = "pixelState.v:24" *)
  DFSRQNX1_CV _661_ (
    .CK(clk),
    .D(_003_[0]),
    .Q(q[1]),
    .QN(_405_),
    .R(reset_c),
    .S(1'h0)
  );
  (* src = "pixelState.v:24" *)
  DFSRQNX1_CV _662_ (
    .CK(clk),
    .D(_005_[2]),
    .Q(q[2]),
    .QN(_406_),
    .R(reset_c),
    .S(1'h0)
  );
  (* src = "pixelState.v:24" *)
  DFSRQNX1_CV _663_ (
    .CK(clk),
    .D(_005_[3]),
    .Q(q[3]),
    .QN(_407_),
    .R(reset_c),
    .S(1'h0)
  );
  (* src = "pixelState.v:24" *)
  DFSRQNX1_CV _664_ (
    .CK(clk),
    .D(_005_[4]),
    .Q(q[4]),
    .QN(_408_),
    .R(reset_c),
    .S(1'h0)
  );
  (* src = "pixelState.v:24" *)
  DFSRQNX1_CV _665_ (
    .CK(clk),
    .D(_005_[5]),
    .Q(q[5]),
    .QN(_409_),
    .R(reset_c),
    .S(1'h0)
  );
  (* src = "pixelState.v:24" *)
  DFSRQNX1_CV _666_ (
    .CK(clk),
    .D(_005_[6]),
    .Q(q[6]),
    .QN(_410_),
    .R(reset_c),
    .S(1'h0)
  );
  (* src = "pixelState.v:24" *)
  DFSRQNX1_CV _667_ (
    .CK(clk),
    .D(_005_[7]),
    .Q(q[7]),
    .QN(_411_),
    .R(reset_c),
    .S(1'h0)
  );
  assign _003_[7] = q[7];
  assign _005_[1] = _003_[0];
  assign enable_counter = 1'h1;
  assign _126_ = _400_;
  assign _064_ = _401_;
  assign _105_ = _402_;
  assign _087_ = _403_;
  assign _005_[0] = _404_;
  assign _380_ = state[1];
  assign _379_ = state[0];
  assign _183_ = _400_;
  assign _008_ = _161_;
  assign _381_ = state[2];
  assign _009_ = _162_;
  assign _006_ = _159_;
  assign _007_ = _160_;
  assign _000_ = _140_;
  assign _002_ = _142_;
  assign _010_ = _163_;
  assign _001_ = _141_;
  assign _370_ = q[0];
  assign _371_ = q[1];
  assign _003_[0] = _143_;
  assign _378_ = reset_c;
  assign _012_ = _167_;
  assign _372_ = q[2];
  assign _003_[1] = _144_;
  assign _013_ = _168_;
  assign _373_ = q[3];
  assign _003_[2] = _145_;
  assign _014_ = _169_;
  assign _374_ = q[4];
  assign _003_[3] = _146_;
  assign _015_ = _170_;
  assign _375_ = q[5];
  assign _003_[4] = _147_;
  assign _016_ = _171_;
  assign _376_ = q[6];
  assign _003_[5] = _148_;
  assign _017_ = _172_;
  assign _377_ = q[7];
  assign _003_[6] = _149_;
  assign _018_ = _173_;
  assign _019_ = _174_;
  assign _020_ = _175_;
  assign _021_ = _176_;
  assign _022_ = _177_;
  assign _023_ = _178_;
  assign _024_ = _179_;
  assign _025_ = _180_;
  assign _026_ = _181_;
  assign _027_ = _182_;
  assign _196_ = gray_counter[1];
  assign _195_ = gray_counter[0];
  assign _197_ = gray_counter[2];
  assign _198_ = gray_counter[3];
  assign _200_ = gray_counter[5];
  assign _199_ = gray_counter[4];
  assign _202_ = gray_counter[7];
  assign _201_ = gray_counter[6];
  assign _367_ = next_state[0];
  assign _184_ = _401_;
  assign _004_[0] = _150_;
  assign _368_ = next_state[1];
  assign _004_[1] = _151_;
  assign _369_ = next_state[2];
  assign _186_ = _403_;
  assign _004_[2] = _152_;
  assign _011_[0] = _164_;
  assign _185_ = _402_;
  assign _011_[1] = _165_;
  assign _011_[2] = _166_;
  assign _005_[2] = _153_;
  assign _005_[3] = _154_;
  assign _005_[4] = _155_;
  assign _005_[5] = _156_;
  assign _005_[6] = _157_;
  assign _005_[7] = _158_;
  assign _194_ = clk;
  assign _417_ = _187_;
  assign _418_ = _188_;
  assign _419_ = _189_;
  assign _420_ = _190_;
  assign _421_ = _191_;
  assign _422_ = _192_;
  assign _423_ = _193_;
endmodule
